name: Update HTML Index

on:
  push:
    branches:
      - main  # Vérifiez que votre branche s'appelle bien 'main' et non 'master'
    paths:
      - 'data/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    # ESSENTIEL : Donner la permission d'écrire dans le dépôt
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Récupère tout l'historique pour éviter des erreurs au push

      - name: Update index.json
        run: |
          # On entre
